# -*- coding: utf-8 -*-
"""ContadorFor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mwja8gYtmr0E2A6vnpWEyT_6e6tZLQPA
"""

for i in range(20, 0, -1):
    if i != 13:
        print(i)