# -*- coding: utf-8 -*-
"""Contador1While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m58kLIxumKBWmM8nOX3hK77uLpWPdx98
"""

i = 20
while i >= 1:
    if i != 13:
        print(i)
    i -= 1